name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd $GITHUB_WORKSPACE

          dotnet sonarscanner begin \
            /k:"DiplomaProjectCSharpByChatGPT" \
            /o:"mateuszsokol" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.login="$SONAR_TOKEN"

          dotnet build DiplomaProjects.sln --no-incremental

          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
